config/routes.rb
Waystation::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users do
    collection do
      get 'new_initial'
      post 'create_initial'
    end
  end

  resources :referrals do
    member do
      get 'download'
    end
  end

  match "test_exception_notification" => "application#test_exception_notification"

  root :to => "pages#root"

end

app/models/user.rb
class User < ActiveRecord::Base
  model_stamper

  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation, :user_type

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of     :username
  validates_uniqueness_of   :username, :email, :allow_blank => true
  validates_format_of       :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of       :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :allow_blank => true
  validates_presence_of     :password, :on => :create
  validates_confirmation_of :password
  validates_length_of       :password, :minimum => 4, :allow_blank => true
  validates_presence_of     :user_type

  def self.user_types
    ['Outside User','Service Center User','Admin','Coach']
  end
  validates_inclusion_of    :user_type, :in => self.user_types
  
  scope :active, where(:active => true)

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
  
  def admin?
    user_type == 'Admin'
  end

  def inside_user?
    ['Service Center User','Admin','Coach'].include? user_type
  end

  def outside_user?
    user_type == 'Outside User'
  end

  def coach?
    ['Admin','Coach'].include? user_type
  end


  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :login_required, :except => [:new_initial, :create_initial]

  def index
    @users = @users.order(:username).all
  end

  def new_initial
    if User.count > 0 then
      if logged_in?
        redirect_to root_url
      else
        redirect_to login_url, :alert => "You must first log in or sign up before accessing this page."
      end
    else
      @user = User.new
    end
  end

  def create_initial
    if User.count > 0 then
      if logged_in?
        redirect_to root_url
      else
        redirect_to login_url, :alert => "You must first log in or sign up before accessing this page."
      end
    else
      @user = User.new(params[:user])
      @user.active = true
      @user.user_type = 'Admin'
      if @user.save
        redirect_to users_path, :notice => "New user successfully created."
      else
        render :action => 'new'
      end
    end
  end

  def new
  end

  def create
    if @user.save
      redirect_to users_path, :notice => "New user successfully created."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      if current_user.admin?
        redirect_to users_path, :notice => "User successfully updated."
      else
        redirect_to root_path, :notice => "Profile successfully updated."
      end
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_messages %>
  <%= f.input :username, :input_html => {:size => 25} %>
  <%= f.input :email, :input_html => {:size => 25}  %>
  <%= f.input :user_type, :collection => User.user_types if current_user.admin? %>
  <%= f.input :active if current_user.admin? %>
  <%= f.input :password, :input_html => {:size => 25}  %>
  <%= f.input :password_confirmation, :input_html => {:size => 25}  %>
  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<% title "Update User" %>

<%= render 'form' %>

app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>User Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th>Active?</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.user_type %></td>
      <td><%= user.active ? 'Yes' : 'No' %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<% title "Add New User" %>

<%= render 'form' %>

app/views/users/new_initial.html.erb
<% title "Add First User" %>

<%= simple_form_for @user, :url => create_initial_users_path(@user) do |f| %>
  <%= f.error_messages %>
  <%= f.input :username, :size => 25, :input_html => {:size => 25} %>
  <%= f.input :email, :input_html => {:size => 25}  %>
  <%= f.input :password, :input_html => {:size => 25}  %>
  <%= f.input :password_confirmation, :input_html => {:size => 25}  %>
  <%= f.button :submit %>
<% end %>