config/routes.rb
Waystation::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users do
    collection do
      get 'new_initial'
      post 'create_initial'
    end
  end

  resources :referrals do
    member do
      get 'download'
    end
  end

  match "test_exception_notification" => "application#test_exception_notification"

  root :to => "pages#root"

end

app/models/referral.rb
class Referral < ActiveRecord::Base
  stampable :stamper_class_name => :user,
                    :creator_attribute  => :created_by,
                    :updater_attribute  => :updated_by
  #attr_accessible :first_name, :last_name, :customer_phone, :case_manager_name, :case_manager_email, :note

  belongs_to :creator, :class_name => 'User', :foreign_key => :created_by
  belongs_to :updater, :class_name => 'User', :foreign_key => :updated_by

  has_attached_file :ucr_form, 
      :path => ":rails_root/uploads/:class/:id/:basename.:extension",
      :url => "/referrals/:id/download"

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :customer_phone
  validates_presence_of :case_manager_name
  validates_presence_of :case_manager_email
  #validates_attachment_presence :ucr_form

  scope :created_by_outside_user, joins(:creator).where(:users => {:user_type => 'Outside User'})
  scope :created_by_inside_user, joins(:creator).where(:users => {:user_type => ['Service Center User','Admin','Coach']})
  scope :created_by, lambda {|user| where(:created_by => user.id)}
  scope :not_completed, where(:completed_at => nil)
  scope :completed, where("referrals.completed_at IS NOT NULL")
  
  def name
    "#{last_name}, #{first_name}"
  end

  def completed
    !completed_at.nil?
  end

  def completed=(value)
    if value == "1" || value == true
      self.completed_at = Time.now if self.completed_at.nil?
    else
      self.completed_at = nil
    end
  end
end

app/controllers/referrals_controller.rb
class ReferralQuery
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_reader :creator_type, :completed 

  CREATOR_TYPE_OPTIONS = %w{all inside outside}
  COMPLETED_OPTIONS = %w{all completed not_completed}

  def initialize(params,session,user)
    params ||= {}

    @creator_type = params[:creator_type] || session[:creator_type] || 'all'
    @completed = params[:completed] || session[:completed] || 'all'
    @current_user = user
    session[:creator_type] = @creator_type
    session[:completed] = @completed
  end

  def persisted?
    false
  end

  def apply_conditions(referrals)
    referrals = referrals.created_by(@current_user) if creator_type == 'user'
    referrals = referrals.created_by_outside_user if creator_type == 'outside' 
    referrals = referrals.created_by_inside_user if creator_type == 'inside'
    referrals = referrals.completed if completed == 'completed'
    referrals = referrals.not_completed if completed == 'not_completed'
    referrals
  end
end

class ReferralsController < ApplicationController
  load_and_authorize_resource
  before_filter :login_required

  def index
    @query = ReferralQuery.new(params[:query],session,current_user)
    @referrals = @query.apply_conditions(@referrals).order('created_at DESC')
  end

  def show
  end

  def new
  end

  def create
    if @referral.save
      redirect_to @referral, :notice => "Successfully created referral."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @referral.update_attributes(params[:referral])
      redirect_to @referral, :notice  => "Successfully updated referral."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @referral.active = false
    @referral.save!
    redirect_to referrals_url, :notice => "Successfully destroyed referral."
  end

  def download
    send_file @referral.ucr_form.path, :type => @referral.ucr_form_content_type, :disposition => 'inline', :x_sendfile => true
  end
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/referrals/_form.html.erb
<%= simple_form_for(@referral, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>
  <%= f.input :first_name, :input_html => {:size => 35} %>
  <%= f.input :last_name, :input_html => {:size => 35} %>
  <%= f.input :customer_phone, :input_html => {:size => 35} %>
  <%= f.input :case_manager_name, :input_html => {:size => 35} %>
  <%= f.input :case_manager_email, :input_html => {:size => 35} %>
  <%= f.input :note %>
  <%= f.input :completed if current_user.coach? %>
  <%= f.input :active if current_user.admin? %>
  <%= f.input :ucr_form %>
  <%= f.button :submit %>
<% end %>

app/views/referrals/edit.html.erb
<% title "Edit Referral" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @referral %> |
  <%= link_to "View All", referrals_path %>
</p>

app/views/referrals/index.html.erb
<% title "Referrals" %>

<% if current_user.inside_user? %>
  <form id="search-form" class="search">
    <fieldset>
      <div class="title">Referrals created by:</div>
      <%= radio_button :query, :creator_type, :user %>
      <%= label :query, :creator_type, "Me", :value => :user %>
      <%= radio_button :query, :creator_type, :inside %>
      <%= label :query, :creator_type, "Ride Connection users", :value => :inside %>
      <%= radio_button :query, :creator_type, :outside %>
      <%= label :query, :creator_type, "Outside users", :value => :outside %>
      <%= radio_button :query, :creator_type, :all %>
      <%= label :query, :creator_type, "Anyone", :value => :all %>
      <br>
      <div class="title">Completion:</div>
      <%= radio_button :query, :completed, :completed %>
      <%= label :query, :completed, "Completed", :value => :completed %>
      <%= radio_button :query, :completed, :not_completed %>
      <%= label :query, :completed, "Not Completed", :value => :not_completed %>
      <%= radio_button :query, :completed, :all %>
      <%= label :query, :completed, "All", :value => :all %>
    </fieldset>
  </form>
<% end %>

<table>
  <tr>
    <th>Submitted</th>
    <% if current_user.coach? %>
      <th>Submitter</th>
    <% end %>
    <th>Customer</th>
    <th>Case Manager</th>
    <th>Note</th>
    <th>Completed</th>
    <% if current_user.admin? %>
      <th>Active</th>
    <% end %>
    <th colspan="4" />
  </tr>
  <% for referral in @referrals %>
    <tr>
      <td><%= referral.created_at %></td>
      <% if current_user.coach? %>
        <td><%= referral.creator.try :username %></td>
      <% end %>
      <td><%= referral.name %></td>
      <td><%= mail_to referral.case_manager_email, referral.case_manager_name %></td>
      <td><%= truncate referral.note %></td>
      <td><%= referral.completed ? 'Yes' : 'No' %></td>
      <% if current_user.admin? %>
        <td><%= referral.active ? 'Yes' : 'No' %></td>
      <% end %>
      <td><%= link_to("UCR Form", image_path(referral.ucr_form.url)) if referral.ucr_form.present? %></td>
      <td><%= link_to "Show", referral %></td>
      <td><%= link_to "Edit", edit_referral_path(referral) if can? :edit, referral %></td>
      <td><%= link_to "Destroy", referral, :confirm => 'Are you sure?', :method => :delete if can? :destroy, referral %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Referral", new_referral_path %></p>

app/views/referrals/new.html.erb
<% title "New Referral" %>

<%= render 'form' %>

<p><%= link_to "Back to List", referrals_path %></p>

app/views/referrals/show.html.erb
<% title "Referral" %>

<p>
  <strong>First Name:</strong>
  <%= @referral.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @referral.last_name %>
</p>
<p>
  <strong>Customer Phone:</strong>
  <%= @referral.customer_phone %>
</p>
<p>
  <strong>Case Manager Name:</strong>
  <%= @referral.case_manager_name %>
</p>
<p>
  <strong>Case Manager Email:</strong>
  <%= mail_to @referral.case_manager_email %>
</p>
<p>
  <strong>Note:</strong>
  <%= simple_format @referral.note %>
</p>
<p>
  <strong>Completed at:</strong>
  <%= @referral.completed_at %>
</p>
<% if current_user.admin? %>
  <p>
    <strong>Active:</strong>
    <%= @referral.active ? 'Yes' : 'No' %>
  </p>
<% end %>

<p>
  <% if @referral.ucr_form.present? %>
    <%= link_to "UCR Form", image_path(@referral.ucr_form.url) %>
  <% else %>
    (No UCR form uploaded)
  <% end %>
</p>

<p>
  <strong>Created:</strong>
  <%= @referral.created_at %> by <%= @referral.creator.username %>
</p>
<% if @referral.updated_at != @referral.created_at %>
  <p>
    <strong>Updated:</strong>
    <%= @referral.updated_at %> by <%= @referral.updater.username %>
  </p>
<% end %>

<p>
  <%= link_to "Edit", edit_referral_path(@referral) %> |
  <%= link_to "Destroy", @referral, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", referrals_path %>
</p>